### ISSUE TITLE
why is `assign_to_search` unsafe?

### ISSUE THREAD

**Issue by fuqcool** [mozfreddyb/eslint-plugin-scanjs-rules#7]
```
 141:13  error    Assignment to search can be unsafe             scanjs-rules/assign_to_search
```

@mozfreddyb can you explain why search is unsafe?

**Comment by mozfreddyb** [comment]
As mentioned somewhere (I hope), many of the rule violations are not inherently unsafe.
The tool flags things that are potentially interesting. The search attribute here is about `location.search`, which can be a DOM XSS source.

**Comment by fuqcool** [comment]
@mozfreddyb Thank you for the response. That's very helpful.
